import type { Metadata } from 'next';
import { Bebas_Neue } from 'next/font/google';
import './reset.css';
import './globals.css';
import { Header } from '@/components/Header/Header';

const bebas = Bebas_Neue({
	weight: ['400'],
	style: ['normal'],
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={bebas.className}>
				<div className={'container'}>
					<Header />
					{children}
				</div>
			</body>
		</html>
	);
}
